"""empty message

Revision ID: 930422a9b7b7
Revises: e2a8f0e527a8
Create Date: 2023-11-30 15:33:52.268933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '930422a9b7b7'
down_revision: Union[str, None] = 'e2a8f0e527a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('post_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('user_id', 'post_id')
                    )
    op.drop_table('products')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('is_sold', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False,
                              nullable=True),
                    sa.Column('inventory', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False,
                              nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'),
                              autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='products_pkey')
                    )
    op.drop_table('votes')
    # ### end Alembic commands ###
